apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: exclusive-web
  name: exclusive-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exclusive-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: exclusive-web
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: my-password
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-data"
          readOnly: true
status: {}

