apiVersion: v1
kind: Service
metadata:
  name: webserver-canary-svc
  labels:
    rollout: canary
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    rollout: canary
status:
  loadBalancer: {}